spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/studyscheduler
    username: studyscheduler
    password: zxcv1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false

server:
  servlet:
    encoding:
      force-response: true

access-secret-key: ${ACCESS_SECRET_KEY}
access-expiration-hours: 1800
refresh-expiration-hours: 86400
issuer: jonghun