spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  # DB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/studyscheduler
    username: studyscheduler
    password: zxcv1234
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
  # data.sql 사용x - local, prod
  sql:
    init:
      mode: never

  devtools:
    restart:
      enabled: true

# JWT
secret-key: ${ACCESS_SECRET_KEY}
access-expiration-hours: 86400
refresh-expiration-hours: 86400
issuer: jonghun